/**
 * RFQ email delivery — env-gated SMTP notification to the parts desk.
 *
 * SECURITY / DATA PROTECTION:
 * - Credentials come ONLY from environment variables (SMTP_HOST, SMTP_PORT,
 *   SMTP_USER, SMTP_PASS, RFQ_NOTIFY_TO, RFQ_NOTIFY_FROM) — never the repo.
 * - Unconfigured (the default), delivery is a silent no-op: the RFQ is still
 *   persisted and visible in the ops desk, so nothing is lost.
 * - Delivery failures NEVER fail the customer's request, and no PII is ever
 *   logged — the audit trail records only mail_sent / mail_error events.
 * - The email goes to JM's own desk inbox; customers are not auto-emailed
 *   (auto-replies invite spam amplification — see LAUNCH.md).
 */

import nodemailer from "nodemailer";
import { audit } from "@/lib/auditLog";
import type { StoredRfq } from "@/lib/rfqStore";

export function mailConfigured(): boolean {
  return Boolean(process.env.SMTP_HOST && process.env.RFQ_NOTIFY_TO);
}

/** Plain-text desk notification. Pure — unit-tested without a transport. */
export function formatRfqEmail(rfq: StoredRfq): { subject: string; text: string } {
  const c = rfq.contact;
  const lines = [
    `New quote request ${rfq.ref}${rfq.freight ? " — FREIGHT QUOTE REQUIRED" : ""}`,
    `Received: ${rfq.createdAt}`,
    "",
    `Company:  ${c.company}`,
    `Contact:  ${[c.name, c.lastName].filter(Boolean).join(" ")}`,
    `Email:    ${c.email}`,
  ];
  if (c.phone) lines.push(`Phone:    ${c.phone}${c.phoneExt ? ` ext. ${c.phoneExt}` : ""}`);
  if (c.serial) lines.push(`Serial:   ${c.serial}`);
  if (c.shipAddress) lines.push(`Ship to:  ${c.shipAddress}`);
  if (c.billingSameAsShipping === false && c.billingAddress) lines.push(`Bill to:  ${c.billingAddress}`);
  if (c.wantsAccount === false) lines.push("Account:  customer opted OUT of an account");
  lines.push("", "Items:");
  for (const it of rfq.items) lines.push(`  ${it.sku}  × ${it.qty}`);
  if (rfq.message) lines.push("", "Message:", `  ${rfq.message}`);
  lines.push(
    "",
    `Work this request in the ops desk: /ops (ref ${rfq.ref}).`,
    "This notification was generated by the parts store; reply goes to the customer address above.",
  );
  return {
    subject: `[RFQ] ${rfq.ref} — ${c.company}${rfq.freight ? " (freight)" : ""}`,
    text: lines.join("\n"),
  };
}

/**
 * Send the desk notification. Fire-and-forget safe: never throws, never
 * blocks or fails the customer response, no PII in logs.
 */
export async function sendRfqNotification(rfq: StoredRfq): Promise<boolean> {
  if (!mailConfigured()) return false;
  try {
    const port = Number(process.env.SMTP_PORT || 587);
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port,
      secure: port === 465,
      auth: process.env.SMTP_USER
        ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS ?? "" }
        : undefined,
    });
    const { subject, text } = formatRfqEmail(rfq);
    await transporter.sendMail({
      from: process.env.RFQ_NOTIFY_FROM || process.env.SMTP_USER || "parts-store@jmequipment.net",
      to: process.env.RFQ_NOTIFY_TO,
      replyTo: rfq.contact.email,
      subject,
      text,
    });
    audit("mail_sent");
    return true;
  } catch {
    // No PII, no error detail with addresses — the RFQ is safe in the store.
    audit("mail_error");
    console.error(`[mail] delivery failed for ${rfq.ref} — RFQ persisted; check SMTP_* configuration`);
    return false;
  }
}
