/**
 * JME Quote Center — seed data, ported VERBATIM from the design handoff
 * (JME Quote Center.dc.html — _SEED_CAT, seedClients, seedQuotes, defaults,
 * TERM_TPL, DISCLOSURES, LOSS_REASONS). Photo paths remapped to /public.
 *
 * INTERNAL: machine base prices and quote values are dealer pricing —
 * server/ops-gated use only.
 */
import type { QcClient, QcMachine, QcQuote, QcSettings } from "./types";

export const SEED_CATALOG: QcMachine[] = [
    {id:'vcs-12-75',cat:'Core Processing',badge:'JME-Manufactured',sku:'JME-VCS12-75',name:'Vertical Core Splitter',sub:'12" Head \u00b7 75" Frame',desc:'Hydraulic single-stroke vertical core splitter engineered for high-volume OCC/kraft core processing. Eliminates dumpster haul costs and converts spent cores to recyclable material in under 30 seconds.',specs:[{k:'Power',v:'5 HP / 230V / 1PH / 60Hz'},{k:'Controller',v:'AB Micro 810 PLC'},{k:'Footprint',v:'30 \u00d7 30 in'},{k:'Max Height',v:'13 ft'},{k:'Noise Level',v:'< 78 dB @ 1m'},{k:'Wall Capacity',v:'\u00bc \u2013 \u215d in'}],base:17500,crating:800,warranty:'1 Year',lead:'10\u201312 Weeks',photo:'/images/core-splitter.png',payment:'50-50',isImport:false,roi:true,pkg:['4 cutter blades','4 blade holder blocks','Instruction manual','Wiring harness','Hydraulic oil / filters','Pre-programmed limits'],cfg:{title:'Configure Core Splitter',sku:'JME-VCS{head}-{frame}',subtitle:'{head}" Head · {frame}" Frame',axes:[{key:'head',label:'Core Head',default:'12',specLabel:'Core Head',options:[{v:'8',label:'8"'},{v:'10',label:'10"'},{v:'12',label:'12"'},{v:'14',label:'14"'}]},{key:'frame',label:'Frame Length',default:'75',priced:true,specLabel:'Frame Length',options:[{v:'45',label:'45"',base:15000,crating:500,cycle:'12 sec',lead:'10–12 Weeks'},{v:'55',label:'55"',base:15500,crating:575,cycle:'15 sec',lead:'10–12 Weeks'},{v:'65',label:'65"',base:16500,crating:675,cycle:'20 sec',lead:'10–12 Weeks'},{v:'75',label:'75"',base:17500,crating:800,cycle:'30 sec',lead:'10–12 Weeks'},{v:'custom',label:'Custom',consult:true,cycle:'Consult',lead:'Consult'}]}],options:[{key:'blades',label:'Spare splitter blade set (4)',amount:740},{key:'holders',label:'Spare knife block holders (4)',amount:960},{key:'head1216',label:'Extra cutting head — 12/16 combo',amount:1430},{key:'consumables',label:'Annual consumables kit (oil + filters)',amount:220},{key:'install',label:'On-site install & startup supervision',amount:2800}]}},
    {id:'sheeter-1650',cat:'Converting Equipment',badge:'Goodstrong / JME',sku:'GMC-TC II 1650',name:'Dual Rotary Sheeter',sub:'Goodstrong 1650 \u00b7 High Speed',desc:'Flagship dual-rotary converting machine. 350 m/min max cutting speed, \u00b10.38 mm single-web accuracy, hydraulic scissors lift, four decurlers, anti-static device. The industry standard for high-volume C1S/C2S converting.',specs:[{k:'Max Speed',v:'350 m/min'},{k:'Web Width',v:'400\u20131,650 mm'},{k:'Cut Length',v:'400\u20131,778 mm'},{k:'Accuracy',v:'\u00b10.38 mm'},{k:'Power',v:'55 kW / 480V / 3PH'},{k:'Roll Capacity',v:'3,200 kg'}],base:495000,crating:0,warranty:'12 Months',lead:'12\u201320 Weeks',photo:'/images/sheeter-1650.jpg',payment:'30-60-10',isImport:true,roi:false,pkg:['Dual rotary knife system','4\u00d7 web decurlers','Hydraulic scissors lift','Anti-static device','Brushless AC servo drive','Automatic stacker & delivery'],cfg:{title:'Configure Sheeter',options:[{key:'decurler',label:'Additional web decurler',amount:6500},{key:'antistatic',label:'Anti-static bar upgrade',amount:3100},{key:'spareknife',label:'Spare rotary knife set',amount:4800},{key:'install',label:'Installation & commissioning supervision',amount:9500},{key:'voltage',label:'Voltage / phase conversion',amount:2400}]}},
    {id:'sheeter-1600e',cat:'Converting Equipment',badge:'Goodstrong / JME',sku:'GMC-TC 1600E',name:'Dual Rotary Sheeter',sub:'Goodstrong 1600E \u00b7 Entry Level',desc:'Best-in-class entry-level dual rotary sheeter. 300 m/min, \u00b10.38 mm accuracy, shaftless dual-position pivoting arm rollstand with 15-ft track, three decurlers, brushless AC servo motor. The ideal first sheeter.',specs:[{k:'Max Speed',v:'300 m/min'},{k:'Web Width',v:'400\u20131,600 mm'},{k:'Cut Length',v:'400\u20131,550 mm'},{k:'Accuracy',v:'\u00b10.38 mm'},{k:'Power',v:'45 kW / 480V / 3PH'},{k:'Roll Capacity',v:'3,200 kg'}],base:372150,crating:0,warranty:'12 Months',lead:'12\u201320 Weeks',photo:'/images/sheeter-1600e.jpg',payment:'30-60-10',isImport:true,roi:false,pkg:['Shaftless pivoting rollstand','15-ft track','3\u00d7 web decurlers','Brushless AC servo motor','Automatic stacker'],cfg:{title:'Configure Sheeter',options:[{key:'decurler',label:'Additional web decurler',amount:6500},{key:'antistatic',label:'Anti-static device',amount:3100},{key:'install',label:'Installation & commissioning supervision',amount:8500},{key:'voltage',label:'Voltage / phase conversion',amount:2400}]}},
    {id:'splicer',cat:'Converting Equipment',badge:'Goodstrong / JME',sku:'GMC-SPLICER',name:'Automatic Corrugator Splicer',sub:'Goodstrong GMC \u00b7 High-Speed',desc:'Pneumatic dual-dancer automatic splice system. 99%+ splice reliability, <10cm paper waste per splice vs. 10m+ manual, proven 35% corrugator speed improvement. Closed-loop tension control for low-grade papers.',specs:[{k:'Splice Reliability',v:'> 99%'},{k:'Waste / Splice',v:'< 10 cm'},{k:'Speed Gain',v:'Up to 35%'},{k:'Tension Control',v:'Closed-loop'},{k:'Dancer',v:'Dual assembly'},{k:'Support',v:'N. America on-site'}],base:0,crating:0,warranty:'12 Months',lead:'Consult',photo:'',payment:'30-60-10',isImport:true,roi:false,pkg:[]},
    {id:'martin-jme',cat:'Roll Handling',badge:'Martin / Refurb',sku:'JME-MARTIN-RFB',name:'Martin Rollstand',sub:'JME-Owned Refurbished',desc:'Pre-owned Martin rollstand refurbished to specification in JME\u2019s Sturgis facility. Buyer-selected brake package, optional accessories, 6-month warranty. Ships 90% assembled.',specs:[{k:'Typical Config',v:'98 \u00d7 60 in'},{k:'Max Roll Weight',v:'7,000 lb / reel'},{k:'Max Speed',v:'1,600+ ft/min'},{k:'Brake Options',v:'Tidland / RE / Renova'},{k:'Lead Time',v:'6\u20138 Weeks'},{k:'FOB',v:'Sturgis, MI'}],base:48500,crating:0,warranty:'6 Months',lead:'6–8 Weeks',photo:'',payment:'50-50',isImport:false,roi:false,pkg:[],cfg:{title:'Configure Rollstand',sku:'JME-MARTIN-RFB',subtitle:'JME-Owned Refurbished',axes:[{key:'brake',label:'Brake Package',default:'re',priced:true,specLabel:'Brake Package',options:[{v:'re',label:'RE Standard',base:48500,note:'Included'},{v:'tid1',label:'Tidland Single',base:50300,note:'+$1,800'},{v:'tid2',label:'Tidland Dual',base:51400,note:'+$2,900'},{v:'rext',label:'RE Extreme XT',base:51900,note:'+$3,400'},{v:'renova',label:'Renova Turborex',base:52400,note:'+$3,900'}]}],options:[{key:'voltage',label:'Voltage conversion (480V/3PH)',amount:2200},{key:'paint',label:'Custom paint & finish',amount:1500}]}},
    {id:'martin-customer',cat:'Roll Handling',badge:'Martin / Rebuild',sku:'JME-MARTIN-RBD',name:'Martin Rollstand Rebuild',sub:'Customer-Owned Refurbishment',desc:'Three-tier rebuild service for customer-owned Martin rollstands. Standard, Enhanced, or Full Restoration. Condition assessments included \u2014 pricing adjusts for heavy damage, frame work, or motor replacement.',specs:[{k:'Standard Rebuild',v:'$28,500'},{k:'Enhanced',v:'$36,500'},{k:'Full Restoration',v:'$44,000'},{k:'Heavy Damage Adj.',v:'+$3,500'},{k:'Frame Straighten',v:'+$2,200'},{k:'Motor Replacement',v:'+$4,800'}],base:28500,crating:0,warranty:'6 Months',lead:'6–8 Weeks',photo:'',payment:'50-50',isImport:false,roi:false,pkg:[],cfg:{title:'Configure Rebuild',sku:'JME-MARTIN-{tier}',subtitle:'{tierLabel} Rebuild',axes:[{key:'tier',label:'Rebuild Tier',default:'standard',priced:true,specLabel:'Rebuild Tier',options:[{v:'standard',label:'Standard',base:28500,warranty:'6 Months',lead:'8–12 Weeks'},{v:'enhanced',label:'Enhanced',base:36500,warranty:'6 Months',lead:'8–12 Weeks'},{v:'full',label:'Full Restoration',base:44000,warranty:'1 Year',lead:'8–12 Weeks'}]}],options:[{key:'heavy',label:'Heavy damage repair',amount:3500},{key:'frame',label:'Frame straightening',amount:2200},{key:'motor',label:'Motor replacement',amount:4800}]}},
    {id:'datien-115e',cat:'Guillotine Cutters',badge:'Datien / JME',sku:'CT-115E',name:'Guillotine Cutter',sub:'Datien CT-115E \u00b7 45" Cut Width',desc:'Computerized heavy-duty paper cutter with 45" cut width. Japan AC servo backgauge with \u00b10.01 mm accuracy. 200-program memory, infrared safety curtain, dual-hand operation. Air-cushion worktable standard.',specs:[{k:'Cut Width',v:'45" (115 cm)'},{k:'Cut Height',v:'16.5 cm'},{k:'Backgauge Acc.',v:'\u00b10.01 mm'},{k:'Memory',v:'200 programs'},{k:'Worktable',v:'Air cushion'},{k:'Safety',v:'Infrared + dual-hand'}],base:0,crating:0,warranty:'12 Months',lead:'Consult',photo:'',payment:'50-50',isImport:true,roi:false,pkg:[]},
    {id:'datien-137e',cat:'Guillotine Cutters',badge:'Datien / JME',sku:'CT-137E',name:'Guillotine Cutter',sub:'Datien CT-137E \u00b7 54" Cut Width',desc:'Mid-range computerized guillotine cutter with 54" cut width. Hydraulic paper lift available. Servo-driven backgauge, electromagnetic clutch for precision braking. Ideal for medium-to-large format converting.',specs:[{k:'Cut Width',v:'54" (137 cm)'},{k:'Backgauge',v:'AC servo'},{k:'Safety',v:'Infrared curtain'},{k:'Memory',v:'Programmable'},{k:'Lifter Option',v:'Left-side hydraulic'},{k:'Air Table',v:'100 \u00d7 100 cm'}],base:0,crating:0,warranty:'12 Months',lead:'Consult',photo:'',payment:'50-50',isImport:true,roi:false,pkg:[]},
    {id:'datien-155e',cat:'Guillotine Cutters',badge:'Datien / JME',sku:'CT-155E',name:'Guillotine Cutter',sub:'Datien CT-155E \u00b7 61" Cut Width',desc:'Large-format computerized guillotine cutter with a 61" cut width. AC servo back-gauge, programmable memory, infrared safety curtain, with optional left-side hydraulic lift and air table.',specs:[{k:'Cut Width',v:'61" (155 cm)'},{k:'Backgauge',v:'AC servo'},{k:'Safety',v:'Infrared curtain'},{k:'Memory',v:'Programmable'},{k:'Lifter Option',v:'Left-side hydraulic'},{k:'Air Table',v:'100 \u00d7 100 cm'}],base:0,crating:0,warranty:'12 Months',lead:'Consult',photo:'',payment:'50-50',isImport:true,roi:false,pkg:[]},
    {id:'linear-dancer',cat:'Accessories',badge:'JME-Manufactured',sku:'JME-LD',name:'Linear Dancer',sub:'Roll-Run Compensation Module',desc:'6" aluminum dynamically-balanced dead-shaft roller assembly that absorbs shock from out-of-round rolls, improves sheet-length control, and reduces scrap. Mounts onto existing sheeter bridge. 1,500 ft/min rated.',specs:[{k:'Roller Dia.',v:'6" aluminum'},{k:'Balance Speed',v:'1,500 ft/min'},{k:'Mounting',v:'Universal bridge'},{k:'Power',v:'None required'},{k:'Application',v:'Any roll-fed line'},{k:'Lead Time',v:'4 Weeks'}],base:0,crating:0,warranty:'1 Year',lead:'4 Weeks',photo:'',payment:'50-50',isImport:false,roi:false,pkg:[]},
    {id:'decurler',cat:'Accessories',badge:'JME-Manufactured',sku:'JME-DCL',name:'JME Decurler',sub:'Multi-Bar Web Decurling System',desc:'Custom-width multi-bar decurler handles clay-in or clay-out wound rolls without mechanical change. Hydlar cradle rollers for maximum bar life, 6" aluminum rollers balanced to 1,200 ft/min. Remote control option available.',specs:[{k:'Roll Direction',v:'Clay-in or -out'},{k:'Roller Dia.',v:'6" aluminum'},{k:'Balance Speed',v:'1,200 ft/min'},{k:'Width',v:'Custom to 80"'},{k:'Power',v:'120V / 1PH'},{k:'Options',v:'Remote, multi-web'}],base:0,crating:0,warranty:'1 Year',lead:'4\u20136 Weeks',photo:'',payment:'50-50',isImport:false,roi:false,pkg:[]},
    {id:'track-trolley',cat:'Material Handling',badge:'JME-Manufactured',sku:'JME-TT-20',name:'Track & Trolley System',sub:'Standard 20-ft Rail System',desc:'Heavy-duty roll-handling track and trolley designed for paper mill roll transport and sheeter staging. Standard 20-ft configuration; custom lengths available. Optional scissor lift tub for inline height adjustment.',specs:[{k:'Standard Length',v:'20 ft'},{k:'Custom Lengths',v:'Available'},{k:'Scissor Lift Tub',v:'$3,500 option'},{k:'Construction',v:'Heavy-duty steel'},{k:'Payment',v:'50 / 50'},{k:'FOB',v:'Sturgis, MI'}],base:0,crating:0,warranty:'Consult',lead:'4 Weeks',photo:'',payment:'50-50',isImport:false,roi:false,pkg:[]},
  ] as unknown as QcMachine[];

export const TERM_TPL: { t: string; d: string }[] = [
    {t:'Quotation Validity',d:'This quotation is valid for {VALIDITY} calendar days from the date of issue. Prices are in USD.'},
    {t:'Equipment Condition',d:'Equipment is sold as specified. Refurbished units per JME condition report; new units per OEM specification.'},
    {t:'FOB Terms',d:'All shipments are FOB {FOB} unless otherwise agreed in writing.'},
    {t:'Warranty Coverage',d:'New JME-manufactured equipment: 1 year. Goodstrong new equipment: 12 months. Martin refurbished: 6 months.'},
    {t:'Warranty Exclusions',d:'Warranty does not cover normal wear, consumables, misuse, unauthorized repair, or modification.'},
    {t:'Freight & Tariffs',d:'Freight and import duties are buyer responsibility unless stated. Tariff rates reflect the rate at time of quote and are subject to change.'},
    {t:'Governing Law',d:'This agreement is governed by the laws of the State of Michigan, United States.'},
    {t:'Acceptance',d:'Equipment ordered or PO issued constitutes acceptance of these terms and conditions.'},
  ];

export const DISCLOSURES: string[] = [
    'Electrical installation: $500\u2013$1,500 (buyer responsibility, not included in quote).',
    'Annual operating cost: $410\u2013$830 (electric, oil, blades, filters).',
    'Site preparation and installation guidance available; on-site install not included.',
    'Freight subject to change. Tariff amounts reflect rate at time of quote; final invoicing per current rate.',
  ];

export const LOSS_REASONS: string[] = ['Price','Lead time','Lost to competitor','Budget / timing','Project cancelled','No decision','Other'];

export function qcDefaults(): QcSettings { return {company:'JM Equipment Inc.',addr:'405\u00bd W. Congress St., Sturgis, MI 49091',phone:'(269) 659-0093',email:'sales@jmequipment.net',fob:'Sturgis, MI',rep:'J. Miller',tariff:15,markup:18,validity:60}; }

export function seedClients(): QcClient[] { return [
    {id:'c1',company:'Acme Container Corp.',contact:'D. Reyes',email:'dreyes@acmecontainer.com',phone:'(419) 555-0142',city:'Toledo, OH',industry:'Corrugated',notes:'Runs two 1650 lines. Interested in core-splitter ROI.'},
    {id:'c2',company:'Great Lakes Paper Co.',contact:'M. Holt',email:'mholt@glpaper.com',phone:'(920) 555-0188',city:'Green Bay, WI',industry:'Paper Mill',notes:'Evaluating a new high-speed sheeter.'},
    {id:'c3',company:'Midwest Carton',contact:'S. Okafor',email:'sokafor@midwestcarton.com',phone:'(317) 555-0119',city:'Indianapolis, IN',industry:'Folding Carton',notes:'Martin rollstand rebuild repeat customer.'},
    {id:'c4',company:'Pinnacle Packaging',contact:'R. Vance',email:'rvance@pinnaclepkg.com',phone:'(901) 555-0173',city:'Memphis, TN',industry:'Print Finishing',notes:'Guillotine cutter shortlist.'},
    {id:'c5',company:'Riverside Converting',contact:'T. Bauer',email:'tbauer@riversideconv.com',phone:'(269) 555-0151',city:'Sturgis, MI',industry:'Specialty Converting',notes:'Local. Decurler + linear dancer upgrade.'},
    {id:'c6',company:'Summit Corrugated',contact:'L. Two Rivers',email:'ltworivers@summitcorr.com',phone:'(404) 555-0166',city:'Atlanta, GA',industry:'Corrugated',notes:'Corrugator splicer evaluation.'},
  ]; }

export function seedQuotes(): QcQuote[] { return [
    {id:'q1',number:'Q-26-0529-76',status:'accepted',machineId:'vcs-12-75',clientCompany:'Acme Container Corp.',clientContact:'D. Reyes',clientDept:'Operations',clientCity:'Toledo, OH 43615',clientEmail:'dreyes@acmecontainer.com',po:'PO-44821',base:17500,crating:800,addons:[],parts:[],payment:'50-50',lead:'10\u201312 Weeks',warranty:'1 Year',validity:60,roiOn:true,roiCores:30,roiDays:250,rep:'J. Miller',notes:'',signedName:'David Reyes',signedDate:'Jun 02, 2026',createdAt:'2026-05-29',followUpDate:'',followUpNote:'',followUpDone:true},
    {id:'q2',number:'Q-26-0512-44',status:'sent',machineId:'sheeter-1650',clientCompany:'Great Lakes Paper Co.',clientContact:'M. Holt',clientDept:'Engineering',clientCity:'Green Bay, WI 54303',clientEmail:'mholt@glpaper.com',po:'',base:495000,crating:0,addons:[],parts:[],payment:'30-60-10',lead:'12\u201320 Weeks',warranty:'12 Months',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'Awaiting install schedule.',signedName:'',signedDate:'',createdAt:'2026-05-12',followUpDate:'2026-06-18',followUpNote:'Call M. Holt re: install schedule & freight',followUpDone:false},
    {id:'q3',number:'Q-26-0603-12',status:'won',machineId:'martin-jme',clientCompany:'Midwest Carton',clientContact:'S. Okafor',clientDept:'Maintenance',clientCity:'Indianapolis, IN 46201',clientEmail:'sokafor@midwestcarton.com',po:'PO-2261',base:48500,crating:0,addons:[{label:'Tidland Dual Brake',amount:2900}],parts:[],payment:'50-50',lead:'6\u20138 Weeks',warranty:'6 Months',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'',signedName:'Sam Okafor',signedDate:'Jun 06, 2026',createdAt:'2026-06-03',followUpDate:'',followUpNote:'',followUpDone:true},
    {id:'q4',number:'Q-26-0418-08',status:'lost',machineId:'datien-115e',clientCompany:'Pinnacle Packaging',clientContact:'R. Vance',clientDept:'Production',clientCity:'Memphis, TN 38114',clientEmail:'rvance@pinnaclepkg.com',po:'',base:62000,crating:0,addons:[],parts:[],payment:'50-50',lead:'14\u201318 Weeks',warranty:'12 Months',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'Lost to competitor on lead time.',signedName:'',signedDate:'',createdAt:'2026-04-18',followUpDate:'',followUpNote:'',followUpDone:true},
    {id:'q5',number:'Q-26-0601-91',status:'draft',machineId:'decurler',clientCompany:'Riverside Converting',clientContact:'T. Bauer',clientDept:'Operations',clientCity:'Sturgis, MI 49091',clientEmail:'tbauer@riversideconv.com',po:'',base:14500,crating:0,addons:[],parts:[],payment:'50-50',lead:'4\u20136 Weeks',warranty:'1 Year',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'Confirm web width.',signedName:'',signedDate:'',createdAt:'2026-06-01',followUpDate:'',followUpNote:'',followUpDone:false},
    {id:'q6',number:'Q-26-0524-33',status:'sent',machineId:'splicer',clientCompany:'Summit Corrugated',clientContact:'L. Two Rivers',clientDept:'Engineering',clientCity:'Atlanta, GA 30318',clientEmail:'ltworivers@summitcorr.com',po:'',base:0,crating:0,addons:[],parts:[],payment:'30-60-10',lead:'Consult',warranty:'12 Months',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'Consultation quote sent.',signedName:'',signedDate:'',createdAt:'2026-05-24',followUpDate:'2026-06-26',followUpNote:'Follow up on splicer consult',followUpDone:false},
    {id:'q7',number:'Q-26-0608-55',status:'draft',machineId:'sheeter-1600e',clientCompany:'Great Lakes Paper Co.',clientContact:'M. Holt',clientDept:'Engineering',clientCity:'Green Bay, WI 54303',clientEmail:'mholt@glpaper.com',po:'',base:372150,crating:0,addons:[],parts:[],payment:'30-60-10',lead:'12\u201320 Weeks',warranty:'12 Months',validity:60,roiOn:false,roiCores:0,roiDays:0,rep:'J. Miller',notes:'Entry-level alternative to 1650.',signedName:'',signedDate:'',createdAt:'2026-06-08',followUpDate:'',followUpNote:'',followUpDone:false},
    {id:'q8',number:'Q-26-0421-19',status:'won',machineId:'vcs-12-75',clientCompany:'Riverside Converting',clientContact:'T. Bauer',clientDept:'Operations',clientCity:'Sturgis, MI 49091',clientEmail:'tbauer@riversideconv.com',po:'PO-7781',base:17500,crating:800,addons:[],parts:[{sku:'JME-VCS-BLD-001',name:'Splitter Blade',qty:4,price:185,rfq:false}],payment:'50-50',lead:'10\u201312 Weeks',warranty:'1 Year',validity:60,roiOn:true,roiCores:24,roiDays:240,rep:'J. Miller',notes:'',signedName:'Tom Bauer',signedDate:'Apr 25, 2026',createdAt:'2026-04-21',followUpDate:'',followUpNote:'',followUpDone:true},
  ] as unknown as QcQuote[]; }
