/**
 * Quote Center seed equipment catalog — INTERNAL PRICING, server-side only.
 *
 * Ported from the JME Quote Center design handoff (the desk's own pricing
 * sheet). This module must NEVER be imported from a client component or any
 * public page: it is served exclusively through the ops-authenticated API and
 * stored in gitignored `.data/`. A regression test asserts no figure from
 * this file appears in any client JS chunk. Edit pricing via the API (or
 * regenerate `.data/quotecenter.json`); this seed only applies on first run.
 *
 * base = 0 → "By Consultation". cost defaults to 72% of base at quote time.
 */

import type { QcMachine } from "./pricing";
export type { QcMachine } from "./pricing";

export const SEED_MACHINES: QcMachine[] = [
  {
    id: "vcs-12-75",
    cat: "Core Processing",
    badge: "JME-Manufactured",
    sku: "JME-VCS12-75",
    name: "Vertical Core Splitter",
    sub: '12" Head · 75" Frame',
    desc: "Hydraulic single-stroke vertical core splitter engineered for high-volume OCC/kraft core processing. Eliminates dumpster haul costs and converts spent cores to recyclable material in under 30 seconds.",
    specs: [
      { k: "Power", v: "5 HP / 230V / 1PH / 60Hz" },
      { k: "Controller", v: "AB Micro 810 PLC" },
      { k: "Footprint", v: "30 × 30 in" },
      { k: "Max Height", v: "13 ft" },
      { k: "Noise Level", v: "< 78 dB @ 1m" },
      { k: "Wall Capacity", v: "¼ – ⅝ in" },
    ],
    base: 17500,
    crating: 800,
    warranty: "1 Year",
    lead: "10–12 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: ["4 cutter blades", "4 blade holder blocks", "Instruction manual", "Wiring harness", "Hydraulic oil / filters", "Pre-programmed limits"],
    options: [
      { key: "blades", label: "Spare splitter blade set (4)", amount: 740 },
      { key: "holders", label: "Spare knife block holders (4)", amount: 960 },
      { key: "head1216", label: "Extra cutting head — 12/16 combo", amount: 1430 },
      { key: "consumables", label: "Annual consumables kit (oil + filters)", amount: 220 },
      { key: "install", label: "On-site install & startup supervision", amount: 2800 },
    ],
  },
  {
    id: "sheeter-1650",
    cat: "Converting Equipment",
    badge: "Goodstrong / JME",
    sku: "GMC-TC II 1650",
    name: "Dual Rotary Sheeter",
    sub: "Goodstrong 1650 · High Speed",
    desc: "Flagship dual-rotary converting machine. 350 m/min max cutting speed, ±0.38 mm single-web accuracy, hydraulic scissors lift, four decurlers, anti-static device. The industry standard for high-volume C1S/C2S converting.",
    specs: [
      { k: "Max Speed", v: "350 m/min" },
      { k: "Web Width", v: "400–1,650 mm" },
      { k: "Cut Length", v: "400–1,778 mm" },
      { k: "Accuracy", v: "±0.38 mm" },
      { k: "Power", v: "55 kW / 480V / 3PH" },
      { k: "Roll Capacity", v: "3,200 kg" },
    ],
    base: 495000,
    crating: 0,
    warranty: "12 Months",
    lead: "12–20 Weeks",
    payment: "30-60-10",
    isImport: true,
    pkg: ["Dual rotary knife system", "4× web decurlers", "Hydraulic scissors lift", "Anti-static device", "Brushless AC servo drive", "Automatic stacker & delivery"],
    options: [
      { key: "decurler", label: "Additional web decurler", amount: 6500 },
      { key: "antistatic", label: "Anti-static bar upgrade", amount: 3100 },
      { key: "spareknife", label: "Spare rotary knife set", amount: 4800 },
      { key: "install", label: "Installation & commissioning supervision", amount: 9500 },
      { key: "voltage", label: "Voltage / phase conversion", amount: 2400 },
    ],
  },
  {
    id: "sheeter-1600e",
    cat: "Converting Equipment",
    badge: "Goodstrong / JME",
    sku: "GMC-TC 1600E",
    name: "Dual Rotary Sheeter",
    sub: "Goodstrong 1600E · Entry Level",
    desc: "Best-in-class entry-level dual rotary sheeter. 300 m/min, ±0.38 mm accuracy, shaftless dual-position pivoting arm rollstand with 15-ft track, three decurlers, brushless AC servo motor. The ideal first sheeter.",
    specs: [
      { k: "Max Speed", v: "300 m/min" },
      { k: "Web Width", v: "400–1,600 mm" },
      { k: "Cut Length", v: "400–1,550 mm" },
      { k: "Accuracy", v: "±0.38 mm" },
      { k: "Power", v: "45 kW / 480V / 3PH" },
      { k: "Roll Capacity", v: "3,200 kg" },
    ],
    base: 372150,
    crating: 0,
    warranty: "12 Months",
    lead: "12–20 Weeks",
    payment: "30-60-10",
    isImport: true,
    pkg: ["Shaftless pivoting rollstand", "15-ft track", "3× web decurlers", "Brushless AC servo motor", "Automatic stacker"],
    options: [
      { key: "decurler", label: "Additional web decurler", amount: 6500 },
      { key: "antistatic", label: "Anti-static device", amount: 3100 },
      { key: "install", label: "Installation & commissioning supervision", amount: 8500 },
      { key: "voltage", label: "Voltage / phase conversion", amount: 2400 },
    ],
  },
  {
    id: "splicer",
    cat: "Converting Equipment",
    badge: "Goodstrong / JME",
    sku: "GMC-SPLICER",
    name: "Automatic Corrugator Splicer",
    sub: "Goodstrong GMC · High-Speed",
    desc: "Pneumatic dual-dancer automatic splice system. 99%+ splice reliability, <10cm paper waste per splice vs. 10m+ manual, proven 35% corrugator speed improvement. Closed-loop tension control for low-grade papers.",
    specs: [
      { k: "Splice Reliability", v: "> 99%" },
      { k: "Waste / Splice", v: "< 10 cm" },
      { k: "Speed Gain", v: "Up to 35%" },
      { k: "Tension Control", v: "Closed-loop" },
      { k: "Dancer", v: "Dual assembly" },
      { k: "Support", v: "N. America on-site" },
    ],
    base: 0,
    crating: 0,
    warranty: "12 Months",
    lead: "Consult",
    payment: "30-60-10",
    isImport: true,
    pkg: [],
    options: [],
  },
  {
    id: "martin-jme",
    cat: "Roll Handling",
    badge: "Martin / Refurb",
    sku: "JME-MARTIN-RFB",
    name: "Martin Rollstand",
    sub: "JME-Owned Refurbished",
    desc: "Pre-owned Martin rollstand refurbished to specification in JME's Sturgis facility. Buyer-selected brake package, optional accessories, 6-month warranty. Ships 90% assembled.",
    specs: [
      { k: "Typical Config", v: "98 × 60 in" },
      { k: "Max Roll Weight", v: "7,000 lb / reel" },
      { k: "Max Speed", v: "1,600+ ft/min" },
      { k: "Brake Options", v: "Tidland / RE / Renova" },
      { k: "Lead Time", v: "6–8 Weeks" },
      { k: "FOB", v: "Sturgis, MI" },
    ],
    base: 48500,
    crating: 0,
    warranty: "6 Months",
    lead: "6–8 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: [],
    options: [
      { key: "tid1", label: "Tidland single-caliper brake upgrade", amount: 1800 },
      { key: "tid2", label: "Tidland dual-caliper brake upgrade", amount: 2900 },
      { key: "rext", label: "RE Extreme XT brake upgrade", amount: 3400 },
      { key: "renova", label: "Renova Turborex brake upgrade", amount: 3900 },
      { key: "voltage", label: "Voltage conversion (480V/3PH)", amount: 2200 },
      { key: "paint", label: "Custom paint & finish", amount: 1500 },
    ],
  },
  {
    id: "martin-rebuild",
    cat: "Roll Handling",
    badge: "Martin / Rebuild",
    sku: "JME-MARTIN-RBD",
    name: "Martin Rollstand Rebuild",
    sub: "Customer-Owned Refurbishment",
    desc: "Three-tier rebuild service for customer-owned Martin rollstands: Standard ($28,500 base), Enhanced (+$8,000), or Full Restoration (+$15,500, 1-year warranty). Condition assessment included — adjustments apply for heavy damage, frame work, or motor replacement.",
    specs: [
      { k: "Tiers", v: "Standard / Enhanced / Full" },
      { k: "Assessment", v: "Included" },
      { k: "Lead Time", v: "8–12 Weeks" },
      { k: "Warranty", v: "6 Mo (Full: 1 Yr)" },
    ],
    base: 28500,
    crating: 0,
    warranty: "6 Months",
    lead: "8–12 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: [],
    options: [
      { key: "enhanced", label: "Enhanced tier upgrade", amount: 8000 },
      { key: "full", label: "Full Restoration tier upgrade (1-yr warranty)", amount: 15500 },
      { key: "heavy", label: "Heavy damage repair", amount: 3500 },
      { key: "frame", label: "Frame straightening", amount: 2200 },
      { key: "motor", label: "Motor replacement", amount: 4800 },
    ],
  },
  {
    id: "datien-115e",
    cat: "Guillotine Cutters",
    badge: "Datien / JME",
    sku: "CT-115E",
    name: "Guillotine Cutter",
    sub: 'Datien CT-115E · 45" Cut Width',
    desc: 'Computerized heavy-duty paper cutter with 45" cut width. Japan AC servo backgauge with ±0.01 mm accuracy. 200-program memory, infrared safety curtain, dual-hand operation. Air-cushion worktable standard.',
    specs: [
      { k: "Cut Width", v: '45" (115 cm)' },
      { k: "Cut Height", v: "16.5 cm" },
      { k: "Backgauge Acc.", v: "±0.01 mm" },
      { k: "Memory", v: "200 programs" },
      { k: "Worktable", v: "Air cushion" },
      { k: "Safety", v: "Infrared + dual-hand" },
    ],
    base: 0,
    crating: 0,
    warranty: "12 Months",
    lead: "Consult",
    payment: "50-50",
    isImport: true,
    pkg: [],
    options: [],
  },
  {
    id: "datien-137e",
    cat: "Guillotine Cutters",
    badge: "Datien / JME",
    sku: "CT-137E",
    name: "Guillotine Cutter",
    sub: 'Datien CT-137E · 54" Cut Width',
    desc: "Mid-range computerized guillotine cutter with 54\" cut width. Hydraulic paper lift available. Servo-driven backgauge, electromagnetic clutch for precision braking. Ideal for medium-to-large format converting.",
    specs: [
      { k: "Cut Width", v: '54" (137 cm)' },
      { k: "Backgauge", v: "AC servo" },
      { k: "Safety", v: "Infrared curtain" },
      { k: "Memory", v: "Programmable" },
      { k: "Lifter Option", v: "Left-side hydraulic" },
      { k: "Air Table", v: "100 × 100 cm" },
    ],
    base: 0,
    crating: 0,
    warranty: "12 Months",
    lead: "Consult",
    payment: "50-50",
    isImport: true,
    pkg: [],
    options: [],
  },
  {
    id: "datien-155e",
    cat: "Guillotine Cutters",
    badge: "Datien / JME",
    sku: "CT-155E",
    name: "Guillotine Cutter",
    sub: 'Datien CT-155E · 61" Cut Width',
    desc: 'Large-format computerized guillotine cutter with a 61" cut width. AC servo back-gauge, programmable memory, infrared safety curtain, with optional left-side hydraulic lift and air table.',
    specs: [
      { k: "Cut Width", v: '61" (155 cm)' },
      { k: "Backgauge", v: "AC servo" },
      { k: "Safety", v: "Infrared curtain" },
      { k: "Memory", v: "Programmable" },
      { k: "Lifter Option", v: "Left-side hydraulic" },
      { k: "Air Table", v: "100 × 100 cm" },
    ],
    base: 0,
    crating: 0,
    warranty: "12 Months",
    lead: "Consult",
    payment: "50-50",
    isImport: true,
    pkg: [],
    options: [],
  },
  {
    id: "linear-dancer",
    cat: "Accessories",
    badge: "JME-Manufactured",
    sku: "JME-LD",
    name: "Linear Dancer",
    sub: "Roll-Run Compensation Module",
    desc: '6" aluminum dynamically-balanced dead-shaft roller assembly that absorbs shock from out-of-round rolls, improves sheet-length control, and reduces scrap. Mounts onto existing sheeter bridge. 1,500 ft/min rated.',
    specs: [
      { k: "Roller Dia.", v: '6" aluminum' },
      { k: "Balance Speed", v: "1,500 ft/min" },
      { k: "Mounting", v: "Universal bridge" },
      { k: "Power", v: "None required" },
      { k: "Application", v: "Any roll-fed line" },
      { k: "Lead Time", v: "4 Weeks" },
    ],
    base: 0,
    crating: 0,
    warranty: "1 Year",
    lead: "4 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: [],
    options: [],
  },
  {
    id: "decurler",
    cat: "Accessories",
    badge: "JME-Manufactured",
    sku: "JME-DCL",
    name: "JME Decurler",
    sub: "Multi-Bar Web Decurling System",
    desc: 'Custom-width multi-bar decurler handles clay-in or clay-out wound rolls without mechanical change. Hydlar cradle rollers for maximum bar life, 6" aluminum rollers balanced to 1,200 ft/min. Remote control option available.',
    specs: [
      { k: "Roll Direction", v: "Clay-in or -out" },
      { k: "Roller Dia.", v: '6" aluminum' },
      { k: "Balance Speed", v: "1,200 ft/min" },
      { k: "Width", v: 'Custom to 80"' },
      { k: "Power", v: "120V / 1PH" },
      { k: "Options", v: "Remote, multi-web" },
    ],
    base: 0,
    crating: 0,
    warranty: "1 Year",
    lead: "4–6 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: [],
    options: [],
  },
  {
    id: "track-trolley",
    cat: "Material Handling",
    badge: "JME-Manufactured",
    sku: "JME-TT-20",
    name: "Track & Trolley System",
    sub: "Standard 20-ft Rail System",
    desc: "Heavy-duty roll-handling track and trolley designed for paper mill roll transport and sheeter staging. Standard 20-ft configuration; custom lengths available. Optional scissor lift tub for inline height adjustment.",
    specs: [
      { k: "Standard Length", v: "20 ft" },
      { k: "Custom Lengths", v: "Available" },
      { k: "Scissor Lift Tub", v: "Optional" },
      { k: "Construction", v: "Heavy-duty steel" },
      { k: "Payment", v: "50 / 50" },
      { k: "FOB", v: "Sturgis, MI" },
    ],
    base: 0,
    crating: 0,
    warranty: "Consult",
    lead: "4 Weeks",
    payment: "50-50",
    isImport: false,
    pkg: [],
    options: [],
  },
];
